Feature: Tagging Login Feature


Scenario: Vitals in My Health
    #Given User on the Login page for Vitals in MiDoc Patient Web Apps

 
    Given user entering the email
        

    Then Click on Continue buttonn


    Then user should enter password:
       

    Then Click on Continue to the home page after Login



#@SmokeTest @RegressionTest
#Scenario: Health Page
 #   Then user navigates to My Health Page

#@SmokeTest @RegressionTest
#Scenario: Vitals
 #   Then  user navigates to Vitals

#@SmokeTest
#Scenario: Adds Weight
  #  And the user adds weight data

#@SmokeTest
#Scenario: Adds Height
 #   And the user adds height data

#@RegressionTest
#Scenario: Adds Respiratory
    #And the user adds respiratory data

#@RegressionTest
#Scenario: Adds Body Temperature
 #   And the user adds body temperature data

#@RegressionTest
#Scenario: Adds Oxygen
 #   And the user adds oxygen level data

#@RegressionTest
#Scenario: Adds Blood Pressure
 #   And the user adds blood pressure data

#@RegressionTest
#Scenario: Adds Heart Pressure
  #  And the user adds heart pressure data
